---
- hosts: apt
  become: true
  become_user: sudo
  tasks:
    - name: Update apt cache and upgrade apt packages
      apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 86400 #24H
#- meta: clear_host_errors
