---
- hosts: zypper
  become: true
  become_method: sudo
  tasks:
    - name: Upgrade all packages
      zypper:
        name: "*"
        state: latest
- import_playbook: apt_upgrade.yaml
- import_playbook: dnf_upgrade.yaml
ignore_errors: yes
