---
- hosts: zypper
  ignore_unreachable: yes
  become: true
  become_method: sudo
  tasks:
    - name: Upgrade all packages
      zypper:
        name: "*"
        state: latest
- import_playbook: apt_upgrade.yaml
- import_playbook: dnf_upgrade.yaml
- meta: clear_host_errors

